---

- name: "Get Letsencrypt Certificate and Split into RSA formatted types"
  hosts: LB
  gather_facts: false
  vars_file: 
    - /certautomation/vault/vault.yml
  roles:
    - roles/General/split_pfx
    - roles/F5/upload_certificate