---

- name: Find Active Unit in HA Pair
  bigip_command:
    provider: "{{ provider }}"
    commands:
      - bash -c "cat /var/prompt/ps1"
  register: find_standby
  delegate_to: localhost

- debug:
    var: find_standby

- name: Concat Name and path
  ansible.builtin.set_fact: 
    key_file: "{{ tmp_dir }}{{ pfx_file_name.stdout[:-4] }}-rsa.key"
    cert_file: "{{ tmp_dir }}{{ pfx_file_name.stdout[:-4] }}.crt"
  when: '"Active" in find_standby.stdout[0]'
  delegate_to: localhost

- name: SSL Certificate Upload
  f5networks.f5_modules.bigip_ssl_certificate:
    provider: "{{ provider }}"
    name: "{{ Certificate_Name }}"
    content: "{{ lookup('file', cert_file) }}"
  when: '"Active" in find_standby.stdout[0]'
  delegate_to: localhost

- name: SSL Key Upload
  f5networks.f5_modules.bigip_ssl_key:
    provider: "{{ provider }}"
    name: "{{ Certificate_Name }}"
    content: "{{ lookup('file', key_file) }}"
  when: '"Active" in find_standby.stdout[0]'
  delegate_to: localhost

- name: Create a client SSL profile with a cert/key/chain setting
  f5networks.f5_modules.bigip_profile_client_ssl:
    provider: "{{ provider }}"
    state: present
    name: "{{ Certificate_Name }}_ClientSSL_profile"
    cert_key_chain:
      - cert: "{{ Certificate_Name }}"
        key: "{{ Certificate_Name }}"
  when: '"Active" in find_standby.stdout[0]'
  delegate_to: localhost